{
    "docs": "https://docs.ansible.com/ansible-core/2.15/dev_guide/testing/sanity/import.html", 
    "results": [
        {
            "message": "The test `ansible-test sanity --test import --python 3.7` [[explain](https://docs.ansible.com/ansible-core/2.15/dev_guide/testing/sanity/import.html)] failed with 1 error:", 
            "output": "plugins/modules/ovh/dns/ovh_dns_record.py:84:0: traceback: SyntaxError: from __future__ imports must occur at the beginning of the file"
        }
    ], 
    "verified": false
}
